---
lang: de
---

# Verpflegung

Wir kümmern uns darum, dass für das ganze Wochenende reichlich Essen und Trinken vorhanden ist. Über gemeinsames Zusammenhelfen beim Herrichten/Wegräumen/Abwaschen/Aufräumen freuen wir uns. Wäre super, wenn sich das schön verteilt und nicht immer die gleichen in der Küchen stehen. Wahrscheinlich werden wir am Anfang des Wochenendes eine grobe Aufteilung machen wer wann hilft. 

Folgende Essen sind geplant:

### Freitag

- Abendessen: Es wird verschiedene Gerichte geben (mindestens Gemüsecurry, Pasta mit verschiedenen Saucen). Die Köche sind bereits informiert. Wenn ihr schon gegessen kommt gebt bitte entsprechend in der Umfrage Bescheid.

### Samstag

- Frühstück: Wir werden für das Frühstück einkaufen (Brot/Semmeln + Belag, Milch + Müsli, Tee, Kaffee etc.). Bei Sonderwünschen bitte entweder selbst was mitbringen oder rechtzeitig Bescheid geben. In der Früh bitte einfach selbst herrichten, sich bedienen und wieder wegräumen. Wenn wer mag, gerne auch am Anfang einfach einiges als Buffet raus räumen.
- Mittagssnack: ab 13:00 Uhr wird es als Start der Hochzeit etwas kleines auf die Hand geben
- Abend: Um 18:00 Uhr gibt es ein Catering - keiner muss sich um was kümmern.
- Es gibt noch einen Mitternachtssnack.

### Sonntag

- Frühstück: Wie Samstag, nur dass es ab 10:00 Uhr von Chris & Katharina organisiert ein Weißwurstfrühstück und eine vegetarische Alternative geben wird (Danke!!). Wenn die Kinder also schon um 7:00 Uhr wach sind, gerne selber kümmern und uns nicht wecken. Sonst warten bis es nach Weißwurst riecht. 😉
- Weiter Verpflegung bitte selbst organisiert auf der Heimreise!

Bei besonderen Bedürfnissen beim Essen (Allergien, Unverträglichkeiten ...) gebt das bitte auch in der Umfrage an, damit wir gemeinsam besprechen können wie wir das am besten organisieren - ob ihr selbst etwas mitbringt oder worauf wir achten können.