---
lang: de
---

# Die Unterkunft

Wir verbringen das ganze Wochenende im [Hochkeilhaus](https://www.hochkeil.at/de/hochkeil/unterkuenfte/team-hostel-hochkeilhaus/) und feiern mit euch dort.

## Zimmer

Die Unterkunft ist eher einfach. Es stehen Zimmer verschiedener Größe zur Verfügung, wobei es mehr große als kleine Zimmer gibt. Deshalb werden wir zum Teil auch Leute zusammenlegen müssen - wir geben uns natürlich Mühe, dass es am Ende für alle passt und ihr nicht mit Wildfremden im Zimmer landet. Beschwerden bitte an Wolfi! 😉

Da es sich um ein Selbstversorgerhaus handelt, müssen Handtücher selbst mitgebracht werden. Bettwäsche kann selbst mitgebracht oder für 9 € geliehen werden. Ohropax stellen wir zur Verfügung. Hausschuhe sind bestimmt auch kein Fehler. 

Wir müssen das Haus besenrein verlassen. 

<!-- ```{=html}
<iframe width="780" height="630" src="bettenliste.html" title="Bettenliste"></iframe>
```
 -->
```{r}
#| column: page
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(reactable)
library(reactablefmtr)
library(readxl)


# bettenliste <- read_csv2("C:/Users/wlederer/OneDrive - FMSWM/Privat/Bettenliste.csv")

# /run/media/wlederer/Elements/Projekte/hochzeit_mail/website/Bettenliste


bettenliste <- read_csv2("/run/media/wlederer/Elements/Projekte/hochzeit_mail/website/Bettenliste/Bettenliste_2.csv")
# bettenliste <- read_xls("/run/media/wlederer/Elements/Projekte/hochzeit_mail/website/Bettenliste/Bettenliste_DE.xlsx")



bettenliste |>
  select(Nummer, Bewohner, Stock, Farbe) |>
  reactable(
    pagination = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    theme = reactableTheme(color = "black"),
    columns = list(
        Stock = colDef(name = "Stockwerk", ),
        Nummer = colDef(name = "Zimmernummer"),
        Bewohner = colDef(name = "Belegung")
        ,
        Farbe = colDef(
        name = "Farbe",
        style = function(value) {
            color <- case_when(value == "Blau" ~ "royalblue",
                            value == "Grün" ~ "green",
                            value == "Orange" ~ "orange",
                            value == "Violette" ~ "violet"
                            )
            list(background = color)}
        )
  ))
```

## Gemeinschaftsräume und Aktivitäten

Im Haus gibt es einige größere Aufenthaltsräume, unter Anderem einen Tischtennisraum wo man sich auch ein bisschen austoben kann. Im Erdgeschoss haben wir einen sehr großen Aufenthaltsraum in dem wir essen und zusammensitzen können. Dort findet am Samstag auch die Feier statt. Daneben ist eine große Gastroküche, in der wir uns das ganze Wochenende versorgen können (mehr zu Essen und Trinken [hier](eat_and_drink.qmd)). 

Im Freien gibt es einen (mäßigen) Beachvolleyballplatz, ein Fußballfeld, eine Lagerfeuerstelle für den Philipp, einen kleinen Bach, eine Almwiese und unzählige Möglichkeiten für Spaziergänge mit Blick auf die Mandlwand. 

Wenn einige Tischtennisschläger + Bälle, Volley- und Fußball, Frisbee und natürlich eine Auswahl an Gesellschaftsspielen mitbringen wäre das super.

## Kosten

Für Übernachtung und Verpflegung abseits der Hochzeit selbst wollen wir es gerne einfach halten. Wir bezahlen alles zusammen und freuen uns, wenn ihr euren Kostenanteil an uns überweist. Kinder bis 18 sind kostenlos. Für alle Erwachsene hätten wir an 100 € pro Person für beide Nächte und Verpflegung gedacht, bei nur einer Übernachtung an 70 €. Alle die nur zur Hochzeit kommen bezahlen natürlich nichts. Dazu kommen dann ggf. nur noch die 9 € pro Bettwäsche, falls ihr die bestellen wollt. 

Zahlungsinformationen bekommt ihr vor der Hochzeit per Email.

## Alternative - Unterkunft im Ort

Wer es lieber etwas ruhiger hat, kann alternativ natürlich auch ein Zimmer in einem Hotel in Mühlbach oder Bischofshofen buchen. Wir freuen uns aber natürlich, wenn ihr mit uns im Haus übernachtet. 
