---
lang: de
---

# Ablauf

## Freitag

- ab ca. 11:00 Uhr Ankommen
- Nachmittag gemütlich gemeinsam verbringen
- ca. 18:00 Uhr gemeinsames Abendessen für alle die schon da sind
- Zusammensitzen, Spielen, evtl. Lagerfeuer (nicht zu viel trinken - die Party ist erst morgen!! ;))

## Samstag

- wann immer ihr aufsteht: Frühstück
- Vormittags einfach was lustiges machen, spazieren gehen, Tischtennis oder Beachvolleyball spielen
- ca. 12:00 Uhr Mittagessen (gemeinsam Pizza bestellen)
- danach: Get ready for the Party!!! :)

### Hochzeit

- 13:30 - 14:00 Eintreffen aller Gäste am Ort der Trauung (tba)
- 14:00 Standesamtliche Trauung vor Ort beim Hochkeilhaus
- 14:30 Sektempfang
- 15:30 Gruppenfoto + Fotos Wolfi&Denise
- 16:00 Kaffee und Kuchen
- 18:00 Abendessen
- 19:30 Reden, Spiele, etc.
- 21:00 PAAAARTY!!! 🎉🥳

## Sonntag

- 10:00 Weißwurstfrühstück + vegetarische Alternative
(Wenn die Kinder schon früher was wollen einfach in der Küche selber bedienen)
- Vormittag gemütlich gemeinsam verbringen
- Abreise bis 16:00 Uhr